<?php
declare(strict_types=1);

namespace RusVideoEmbeds\Block;

defined('ABSPATH') || exit;

use RusVideoEmbeds\Embed\EmbedRenderer;
use RusVideoEmbeds\Providers\ProviderRegistry;

/**
 * Registers and renders the rus-video-embeds/video Gutenberg block.
 *
 * Uses server-side rendering (render_callback) so the output in the editor
 * (via ServerSideRender) and the frontend is identical and generated by PHP.
 */
class VideoBlock
{

    /**
     * Registers the block type using block.json metadata.
     *
     * @return void
     */
    public static function register(): void
    {
        register_block_type(
            RUS_VIDEO_EMBEDS_DIR . 'blocks/video',
            [
                'render_callback' => [self::class, 'render'],
            ]
        );
    }

    /**
     * Server-side render callback for the video block.
     *
     * Validates the URL against registered providers and delegates
     * HTML generation to EmbedRenderer. For Dzen watch-URLs, renders
     * an informational notice instead of an empty string.
     *
     * @param array $attributes {
     *     Block attributes saved in the editor.
     *
     *     @type string $url         The video URL.
     *     @type string $aspectRatio Aspect ratio (e.g. "16:9").
     *     @type bool   $autoplay    Whether autoplay is enabled.
     * }
     * @return string Rendered HTML, or an error message if the URL is invalid.
     */
    public static function render(array $attributes): string
    {
        $url = $attributes['url'] ?? '';
        if (empty($url)) {
            return '';
        }

        $registry = ProviderRegistry::getInstance();
        $provider = $registry->findByUrl($url);

        if ($provider === null) {
            return '<p class="rve-error">'
                . esc_html__('Unrecognized URL. Supported: VK Video, Rutube, Dzen', 'rus-video-embeds')
                . '</p>';
        }

        $embedUrl = $provider->getEmbedUrl($url);
        if ($embedUrl === null) {
            if (method_exists($provider, 'isWatchUrl') && $provider->isWatchUrl($url)) {
                return EmbedRenderer::renderNotice(
                    __('Dzen uses separate links for embedding. Click "Share" → "Embed" under the video and copy the link from the iframe code.', 'rus-video-embeds'),
                    EmbedRenderer::getDzenNoticeUrl(),
                    __('Learn more', 'rus-video-embeds')
                );
            }

            return '';
        }

        return EmbedRenderer::render($embedUrl, [
            'aspectRatio' => $attributes['aspectRatio'] ?? '16:9',
            'autoplay'    => !empty($attributes['autoplay']),
            'skipMargin'  => true,
        ]);
    }
}
